public enum ACTION_LOCATION_TYPE
{
	IN_PLACE,
	NEARBY,
	RANDOM_LOCATION,
	RANDOM_LOCATION_B,
	NEAR_TARGET,
	TARGET_IN_VISION,
	OVERRIDE,
	NEAR_OTHER_TARGET,
	UPON_STRUCTURE_ARRIVAL,
	ON_REACH_CORRUPTION
}
