using System;
using System.Collections.Generic;
using UtilityScripts;

public static class ChanceData
{
	public static Dictionary<CHANCE_TYPE, int> integerChances = new Dictionary<CHANCE_TYPE, int>(EnumComparer<CHANCE_TYPE>.Instance)
	{
		{
			CHANCE_TYPE.Kleptomania_Pickpocket_Level_1,
			5
		},
		{
			CHANCE_TYPE.Kleptomania_Pickpocket_Level_2,
			10
		},
		{
			CHANCE_TYPE.Kleptomania_Rob_Other_House,
			5
		},
		{
			CHANCE_TYPE.Kleptomania_Rob_Any_Place,
			5
		},
		{
			CHANCE_TYPE.Lich_Cult_Leader_Spawn,
			50
		},
		{
			CHANCE_TYPE.Laziness_Nap_Level_2,
			2
		},
		{
			CHANCE_TYPE.Laziness_Nap_Level_3,
			4
		},
		{
			CHANCE_TYPE.Unfaithful_Active_Search_Affair,
			20
		},
		{
			CHANCE_TYPE.Ignore_Urgent_Task,
			35
		},
		{
			CHANCE_TYPE.Flirt_Acquaintance_Become_Lover_Chance,
			25
		},
		{
			CHANCE_TYPE.Flirt_Acquaintance_Become_Affair_Chance,
			35
		},
		{
			CHANCE_TYPE.Flirt_Friend_Become_Lover_Chance,
			35
		},
		{
			CHANCE_TYPE.Flirt_Friend_Become_Affair_Chance,
			50
		},
		{
			CHANCE_TYPE.Flirt_Base_Chance,
			1
		},
		{
			CHANCE_TYPE.Vampire_Lord_Chance,
			10
		},
		{
			CHANCE_TYPE.Host_Social_Party,
			5
		},
		{
			CHANCE_TYPE.Demonic_Decor_On_Corrupt,
			15
		},
		{
			CHANCE_TYPE.Retaliation_Character_Death,
			35
		},
		{
			CHANCE_TYPE.Retaliation_Structure_Destroy,
			30
		},
		{
			CHANCE_TYPE.Retaliation_Resource_Pile,
			25
		},
		{
			CHANCE_TYPE.Retaliation_Under_Siege,
			30
		},
		{
			CHANCE_TYPE.Harpy_Capture,
			15
		},
		{
			CHANCE_TYPE.Lycanthrope_Transform_Chance,
			25
		},
		{
			CHANCE_TYPE.Visit_Friend,
			25
		},
		{
			CHANCE_TYPE.Ent_Spawn,
			3
		},
		{
			CHANCE_TYPE.Mimic_Spawn,
			5
		},
		{
			CHANCE_TYPE.Vampire_Lycan_Visit_Hospice,
			5
		},
		{
			CHANCE_TYPE.Settlement_Ruler_Default_Facility_Chance,
			10
		},
		{
			CHANCE_TYPE.Kidnap_Chance,
			35
		},
		{
			CHANCE_TYPE.Raid_Chance,
			25
		},
		{
			CHANCE_TYPE.Find_Fish,
			10
		},
		{
			CHANCE_TYPE.Party_Quest_First_Knockout,
			25
		},
		{
			CHANCE_TYPE.Change_Intent,
			25
		},
		{
			CHANCE_TYPE.Change_Intent_Kleptomania,
			25
		},
		{
			CHANCE_TYPE.Change_Intent_Vampire,
			25
		},
		{
			CHANCE_TYPE.Change_Intent_Cultist,
			25
		},
		{
			CHANCE_TYPE.Change_Intent_Noble,
			50
		},
		{
			CHANCE_TYPE.Change_Intent_Pyromaniac,
			25
		},
		{
			CHANCE_TYPE.Plauged_Injured_Visit_Hospice,
			15
		},
		{
			CHANCE_TYPE.Free_Time_Obtain_Want,
			20
		},
		{
			CHANCE_TYPE.Do_Work_Chance,
			85
		},
		{
			CHANCE_TYPE.Monster_Migration,
			15
		},
		{
			CHANCE_TYPE.Socialize_Chance,
			20
		},
		{
			CHANCE_TYPE.Visit_Village_Chance,
			10
		},
		{
			CHANCE_TYPE.Create_Change_Class_Combatant,
			35
		},
		{
			CHANCE_TYPE.Personal_Combatant_Change_Class,
			5
		},
		{
			CHANCE_TYPE.Kobold_Place_Freezing_Trap,
			10
		},
		{
			CHANCE_TYPE.Base_Create_Faction_Chance,
			5
		},
		{
			CHANCE_TYPE.Vagrant_Join_Or_Create_Faction,
			15
		},
		{
			CHANCE_TYPE.Vampire_Hunt_Drink_Blood_Chance,
			7
		},
		{
			CHANCE_TYPE.Werewolf_Hunt_On_See_Werewolf,
			15
		},
		{
			CHANCE_TYPE.Werewolf_Hunt_Mangled,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Lethargic,
			5
		},
		{
			CHANCE_TYPE.Plagued_Event_Paralyzed,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Heart_Attck,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Pneumonia,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Puke,
			5
		},
		{
			CHANCE_TYPE.Plagued_Event_Seizure,
			5
		},
		{
			CHANCE_TYPE.Plagued_Event_Septic_Shock,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Sneeze,
			5
		},
		{
			CHANCE_TYPE.Plagued_Event_Stroke,
			15
		},
		{
			CHANCE_TYPE.Plagued_Event_Organ_Failure,
			15
		},
		{
			CHANCE_TYPE.Equipment_Prefix_Chance,
			15
		},
		{
			CHANCE_TYPE.Electric_Balls_Chance,
			5
		},
		{
			CHANCE_TYPE.Monster_To_Drop_None,
			1000
		},
		{
			CHANCE_TYPE.War_Declaration_Chance,
			70
		},
		{
			CHANCE_TYPE.Place_Magic_Academy,
			10
		},
		{
			CHANCE_TYPE.Train_Magic_Academy,
			15
		},
		{
			CHANCE_TYPE.Learn_New_Combat_Skill_Magic_Acad,
			25
		},
		{
			CHANCE_TYPE.Devastation_Ritual,
			0
		},
		{
			CHANCE_TYPE.Join_Bandit,
			15
		},
		{
			CHANCE_TYPE.Check_Free_Time_Leave_Party,
			5
		},
		{
			CHANCE_TYPE.Check_Free_Time_Kickout_Party,
			5
		},
		{
			CHANCE_TYPE.Noble_Chance,
			4
		},
		{
			CHANCE_TYPE.Join_Vampire_Clan,
			1
		},
		{
			CHANCE_TYPE.Blood_Hunt_Imprison_Blood_Source,
			10
		},
		{
			CHANCE_TYPE.Barbarian_Escape,
			50
		},
		{
			CHANCE_TYPE.Sapient_Escape,
			1
		},
		{
			CHANCE_TYPE.Shaman_Ritual,
			5
		},
		{
			CHANCE_TYPE.Tame_Beast,
			25
		},
		{
			CHANCE_TYPE.Spawn_Blood_Hunt,
			10
		},
		{
			CHANCE_TYPE.Spawn_Recruit_Vampires,
			5
		},
		{
			CHANCE_TYPE.Vampire_Recruit_Hemophiliac,
			25
		},
		{
			CHANCE_TYPE.Pyromaniac_Arson_Bad_Mood,
			5
		},
		{
			CHANCE_TYPE.Diplomatic_Reduce_Conflict,
			4
		},
		{
			CHANCE_TYPE.Unicorn_Spawn,
			5
		},
		{
			CHANCE_TYPE.Unicorn_Join_Faction,
			10
		},
		{
			CHANCE_TYPE.Place_Barracks,
			10
		},
		{
			CHANCE_TYPE.Learn_New_Combat_Skill_Barracks,
			25
		},
		{
			CHANCE_TYPE.Train_Barracks,
			15
		},
		{
			CHANCE_TYPE.Ratman_Find_Home,
			10
		},
		{
			CHANCE_TYPE.Counterattack,
			40
		},
		{
			CHANCE_TYPE.Create_Food_Pack,
			30
		},
		{
			CHANCE_TYPE.Trigger_Flaw_During_Work,
			4
		},
		{
			CHANCE_TYPE.Mount_Wyvern,
			30
		},
		{
			CHANCE_TYPE.Tend_Wyvern_Coop,
			8
		},
		{
			CHANCE_TYPE.Build_Wyvern_Coop,
			15
		},
		{
			CHANCE_TYPE.Religious_Cult_Leader_Spawn_Chance,
			25
		},
		{
			CHANCE_TYPE.Cult_Leader_Create_Faction,
			1
		},
		{
			CHANCE_TYPE.Spawn_Claim_Hallowed_Ground,
			10
		},
		{
			CHANCE_TYPE.Spawn_Defend_Hallowed_Ground,
			50
		},
		{
			CHANCE_TYPE.Religious_Cult_Raid,
			30
		},
		{
			CHANCE_TYPE.Rarely_Recruits,
			10
		},
		{
			CHANCE_TYPE.Usually_Recruits,
			80
		},
		{
			CHANCE_TYPE.Usually_Keeps,
			100
		},
		{
			CHANCE_TYPE.Check_Recruit_Chance,
			15
		},
		{
			CHANCE_TYPE.Build_Lightning_Tower,
			45
		},
		{
			CHANCE_TYPE.Build_Arrow_Tower,
			45
		},
		{
			CHANCE_TYPE.Build_Beast_Pen,
			25
		},
		{
			CHANCE_TYPE.Claim_Legendary_Forge,
			1
		},
		{
			CHANCE_TYPE.Craft_Legendary_Equipment,
			15
		},
		{
			CHANCE_TYPE.Fang_Affliction,
			1
		},
		{
			CHANCE_TYPE.Citrus_Tame,
			5
		},
		{
			CHANCE_TYPE.Free_Time_Cultist_Do_Cult_Action,
			25
		},
		{
			CHANCE_TYPE.Cultist_Preach,
			80
		},
		{
			CHANCE_TYPE.Cultist_Pilgrimage,
			30
		},
		{
			CHANCE_TYPE.Automatic_Villager_Migration_No_Hostile,
			100
		},
		{
			CHANCE_TYPE.Automatic_Villager_Migration,
			8
		},
		{
			CHANCE_TYPE.Demon_Worship_Crime_On_Imprison,
			30
		},
		{
			CHANCE_TYPE.Obsessed_Visit,
			30
		},
		{
			CHANCE_TYPE.Obsessed_Mummified_Actions,
			30
		},
		{
			CHANCE_TYPE.Release_Mummy_Character,
			30
		},
		{
			CHANCE_TYPE.Release_Mummy_Player,
			60
		},
		{
			CHANCE_TYPE.Watch_Sleep_Weight,
			100
		},
		{
			CHANCE_TYPE.Sniff_Clothes_Weight,
			100
		},
		{
			CHANCE_TYPE.Smell_Hair_Weight,
			100
		},
		{
			CHANCE_TYPE.Lick_Object_Weight,
			100
		},
		{
			CHANCE_TYPE.Rub_Object_Weight,
			100
		},
		{
			CHANCE_TYPE.Nullchild_Migrant,
			3
		},
		{
			CHANCE_TYPE.Jinxed_Migrant,
			2
		},
		{
			CHANCE_TYPE.Demon_Cultist_Preach,
			50
		},
		{
			CHANCE_TYPE.Spawn_Mushroom_Day_Start,
			30
		},
		{
			CHANCE_TYPE.Mushroom_Abomination_Germ,
			3
		},
		{
			CHANCE_TYPE.Idle_Repair_Home,
			25
		},
		{
			CHANCE_TYPE.Spouse_Move_In,
			50
		},
		{
			CHANCE_TYPE.Obsess_Bad_Mood,
			1
		},
		{
			CHANCE_TYPE.Obsess_Critical_Mood,
			5
		},
		{
			CHANCE_TYPE.Wet_Floor_Stumble,
			3
		},
		{
			CHANCE_TYPE.Wet_Stumble,
			3
		},
		{
			CHANCE_TYPE.Change_Intent_Purchase,
			25
		},
		{
			CHANCE_TYPE.Judge_Absolve,
			0
		},
		{
			CHANCE_TYPE.Judge_Whip,
			0
		},
		{
			CHANCE_TYPE.Judge_Execute,
			0
		},
		{
			CHANCE_TYPE.Judge_Exile,
			0
		},
		{
			CHANCE_TYPE.Grudge_Exile_Normal_Mood,
			25
		},
		{
			CHANCE_TYPE.Grudge_Exile_Bad_Mood,
			50
		},
		{
			CHANCE_TYPE.Grudge_Exile_Critical_Mood,
			100
		},
		{
			CHANCE_TYPE.Work_Time_Cultist_Do_Cult_Action,
			15
		},
		{
			CHANCE_TYPE.Socialize_Friend,
			15
		},
		{
			CHANCE_TYPE.Socialize_Friend_Visit,
			30
		},
		{
			CHANCE_TYPE.Goblin_Kill,
			50
		},
		{
			CHANCE_TYPE.Goblin_Impregnate,
			50
		},
		{
			CHANCE_TYPE.Eradication_Spawn_New_Faction,
			50
		}
	};

	public static bool RollChance(CHANCE_TYPE p_chanceType)
	{
		if (integerChances.ContainsKey(p_chanceType))
		{
			return GameUtilities.RollChance(integerChances[p_chanceType]);
		}
		throw new Exception($"No chance set for {p_chanceType}");
	}

	public static bool RollChance(CHANCE_TYPE p_chanceType, ref string log)
	{
		if (integerChances.ContainsKey(p_chanceType))
		{
			return GameUtilities.RollChance(integerChances[p_chanceType], ref log);
		}
		throw new Exception($"No chance set for {p_chanceType}");
	}

	public static int GetChance(CHANCE_TYPE p_chanceType)
	{
		if (integerChances.ContainsKey(p_chanceType))
		{
			return integerChances[p_chanceType];
		}
		throw new Exception($"No chance set for {p_chanceType}");
	}

	public static void SetChance(CHANCE_TYPE p_chanceType, int p_value)
	{
		if (integerChances.ContainsKey(p_chanceType))
		{
			integerChances[p_chanceType] = p_value;
		}
	}
}
