#!/usr/bin/env bash
# One-time setup for IDE/MSBuild use: writes src/Directory.Build.props pointing
# <RuinManaged> at THIS machine's game Managed/ dir (from env.sh). The file is
# gitignored; tracked files stay clean. tools/build.sh never needs this.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/env.sh"
[ -d "$RUIN_MANAGED_DIR" ] || { echo "RUIN_MANAGED_DIR not found: $RUIN_MANAGED_DIR (set RUIN_GAME_DIR)" >&2; exit 1; }
cat > "$RUIN_SRC_DIR/Directory.Build.props" <<PROPS
<Project>
  <PropertyGroup>
    <!-- Generated by tools/fix-csproj-paths.sh; machine-local, not committed. -->
    <RuinManaged>$RUIN_MANAGED_DIR</RuinManaged>
  </PropertyGroup>
</Project>
PROPS
echo "Wrote $RUIN_SRC_DIR/Directory.Build.props -> $RUIN_MANAGED_DIR"
